project:
  type: website
  output-dir: docs

website:
  title: "James Tripp"
  site-url: "https://jamestripp.net"
  search: false
  twitter-card: true
  open-graph: true
  navbar:
    right:
      - icon: linkedin
        href: https://linkedin.com/in/jamestripp/
      - icon: github
        href: https://github.com/jamestripp
      - icon: twitter
        href: https://twitter.com/jamestripp_

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
