baseURL: https://jamestripp.net/
languageCode: en-us
title: James Tripp
theme: archie
copyright: © James Tripp
pygmentsstyle: monokai
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
params:
  mode: auto
  social:
    - icon: github
      name: GitHub
      url: https://github.com/athul/jamestripp
    - icon: twitter
      name: Twitter
      url: https://twitter.com/jamestripp
  subtitle: Senior Academic Technologist, University of Warwick
  useCDN: no
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about
      weight: 3
    - name: Projects
      url: /projects
      weight: 4
