baseurl: "/"
languageCode: "en-us"
title: "James Tripp"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
#    - name: About
#      url: "about/"
#      weight: 2
#    - name: Categories
#      url: "categories/"
#      weight: 3
    - name: Tags
      url: "tags/"
      weight: 2
    - name: Subscribe
      url: "index.xml"

params:
  description: "James Tripp's personal website"
  footer: "&copy; [James Tripp](https://jamestripp.net) 2021 -- 2022 | [Github](https://github.com/jamestripp) | [LinkedIn](https://www.linkedin.com/in/jamestripp/) | [Twitter](https://twitter.com/jamestripp_)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
